<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.280">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Regressie-analyse met R.">

<title>Regressie - 3&nbsp; Categoriale Regressie</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./correlatie.html" rel="next">
<link href="./diagnoses.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Geen resultaten",
    "search-matching-documents-text": "Gevonden documenten",
    "search-copy-link-title": "Kopieer link om te zoeken",
    "search-hide-matches-text": "Extra overeenkomsten verbergen",
    "search-more-match-text": "meer overeenkomst in dit document",
    "search-more-matches-text": "meer overeenkomsten in dit document",
    "search-clear-button-title": "Wissen",
    "search-detached-cancel-button-title": "Annuleren",
    "search-submit-button-title": "Verzenden"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Categoriale Regressie</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Regressie</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Inleiding</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./linmodel.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Lineair model</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./diagnoses.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Diagnostische grafieken</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./catregressie.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Categoriale Regressie</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correlatie.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Correlatie</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./voorwaarden.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Voorwaarden</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./overfitting.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Over- en underfitting</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logitmodel.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Logistisch model</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./voorbeelden.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Voorbeelden</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./referenties.html" class="sidebar-item-text sidebar-link">Referenties</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhoudsopgave</h2>
   
  <ul>
  <li><a href="#data" id="toc-data" class="nav-link active" data-scroll-target="#data"><span class="toc-section-number">3.1</span>  Data</a></li>
  <li><a href="#categorievariabelen-met-2-niveaus" id="toc-categorievariabelen-met-2-niveaus" class="nav-link" data-scroll-target="#categorievariabelen-met-2-niveaus"><span class="toc-section-number">3.2</span>  Categorievariabelen met 2 niveaus</a></li>
  <li><a href="#categorievariabelen-met-meer-dan-2-niveaus" id="toc-categorievariabelen-met-meer-dan-2-niveaus" class="nav-link" data-scroll-target="#categorievariabelen-met-meer-dan-2-niveaus"><span class="toc-section-number">3.3</span>  Categorievariabelen met meer dan 2 niveaus</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="catregressie" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Categoriale Regressie</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Categorische variabelen (ook bekend als factor- of kwalitatieve variabelen) zijn variabelen die waarnemingen in groepen indelen. Ze hebben een beperkt aantal verschillende waarden, niveaus genoemd. Het geslacht van personen is bijvoorbeeld een categorische variabele die twee niveaus kan aannemen: mannelijk of vrouwelijk.</p>
<p>Regressieanalyse vereist numerieke variabelen. Dus wanneer je een categorische variabele in een regressiemodel wilt opnemen moet je deze eerst naar numerieke waarden omzetten. Hiertoe worden de categorische variabelen gehercodeerd in een reeks afzonderlijke binaire variabelen. Bij deze hercodering waarbij <em>dummy-variabelen</em> worden gemaakte heet daarom ook wel <em>dummy-codering</em> en leidt tot het maken van een tabel met de naam <em>contrastmatrix</em>. Dit gebeurt automatisch door statistische software, zoals R.</p>
<p>Voor een uitleg aan de hand van een voorbeeld wordt de dataset <code>Salaries</code> gebruikt (zie <span class="citation" data-cites="kassambaraMachineLearningEssentials2018">[<a href="referenties.html#ref-kassambaraMachineLearningEssentials2018" role="doc-biblioref">11</a>]</span>)</p>
<section id="data" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h2>
<p>Dataset <code>Salaries</code> uit package <code>carData</code> bevat het academisch salaris van negen maanden voor 2008-2009 bevat voor assistent-professoren, universitair hoofddocenten en professoren aan een universiteit in de VS. De gegevens zijn verzameld om o.a. de salarisverschillen tussen mannelijke en vrouwelijke faculteitsleden te controleren.</p>
<p><strong>Variabelen</strong></p>
<ul>
<li><code>rank</code> : rang</li>
<li><code>discipline</code></li>
<li><code>yrs.since.phd</code></li>
<li><code>yrs.service</code> : aantal dienstjaren</li>
<li><code>sex</code> : geslacht</li>
<li><code>salary</code> : salaris</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"Salaries"</span>, <span class="at">package =</span> <span class="st">"carData"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Salaries)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       rank discipline yrs.since.phd yrs.service  sex salary
1      Prof          B            19          18 Male 139750
2      Prof          B            20          16 Male 173200
3  AsstProf          B             4           3 Male  79750
4      Prof          B            45          39 Male 115000
5      Prof          B            40          41 Male 141500
6 AssocProf          B             6           6 Male  97000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(Salaries)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   397 obs. of  6 variables:
 $ rank         : Factor w/ 3 levels "AsstProf","AssocProf",..: 3 3 1 3 3 2 3 3 3 3 ...
 $ discipline   : Factor w/ 2 levels "A","B": 2 2 2 2 2 2 2 2 2 2 ...
 $ yrs.since.phd: int  19 20 4 45 40 6 30 45 21 18 ...
 $ yrs.service  : int  18 16 3 39 41 6 23 45 20 18 ...
 $ sex          : Factor w/ 2 levels "Female","Male": 2 2 2 2 2 2 2 2 2 1 ...
 $ salary       : int  139750 173200 79750 115000 141500 97000 175000 147765 119250 129000 ...</code></pre>
</div>
</div>
</section>
<section id="categorievariabelen-met-2-niveaus" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="categorievariabelen-met-2-niveaus"><span class="header-section-number">3.2</span> Categorievariabelen met 2 niveaus</h2>
<p>Stel dat je het verschil in salaris tussen mannen en vrouwen wilt onderzoeken. De regressievergelijking zou er dan uit kunnen zien als</p>
<p><span class="math inline">\(salary = b_0 + b1*sex\)</span></p>
<p>Echter <code>sex</code> is een categorievariabele met de waarden <code>Male</code> en <code>Female</code>. Daar kun je niet mee rekenen. Op basis van de variabele <code>sex</code> kun je een nieuwe dummy variabele maken met de waarde 1 voor <code>Male</code> en 0 voor <code>Female</code>. Wanneer je deze variabele als voorspeller in de regressievergelijking gaat gebruiken dan kan dat tot het volgende model leiden:</p>
<ul>
<li><span class="math inline">\(salary = b_0 + b1\)</span> als de persoon mannelijk is</li>
<li><span class="math inline">\(salary = b_0\)</span> als de persoon vrouwelijk is</li>
</ul>
<p>De coëfficienten kun je dan als volgt interpreteren.</p>
<ul>
<li><span class="math inline">\(b_0\)</span> is het gemiddelde salaris voor vrouwen</li>
<li><span class="math inline">\(b_0 + b_1\)</span> is het gemiddelde salaris voor mannen</li>
<li><span class="math inline">\(b_1\)</span> is het gemiddelde verschil in salaris tussen mannen en vrouwen</li>
</ul>
<p>Voor eenvoudige demonstratiedoeleinden modelleert het volgende voorbeeld het salarisverschil tussen mannen en vrouwen door een eenvoudig lineair regressiemodel te berekenen voor de dataset <code>Salaries</code>. R maakt automatisch dummy-variabelen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> sex, <span class="at">data =</span> Salaries)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ sex, data = Salaries)

Residuals:
   Min     1Q Median     3Q    Max 
-57290 -23502  -6828  19710 116455 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   101002       4809   21.00   &lt;2e-16 ***
sexMale        14088       5065    2.78   0.0057 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 30000 on 395 degrees of freedom
Multiple R-squared:  0.0192,    Adjusted R-squared:  0.0167 
F-statistic: 7.74 on 1 and 395 DF,  p-value: 0.00567</code></pre>
</div>
</div>
<ul>
<li>101002 is het gemiddelde salaris voor vrouwen</li>
<li>101002 + 14088 = 115090 is het gemiddelde salaris voor mannen</li>
</ul>
<p>De p-waarde voor de dummyvariabele <code>sexMale</code> is zeer significant, wat suggereert dat er statistisch gezien een verschil in gemiddeld salaris tussen de geslachten is.</p>
<p>De functie <code>contrasts()</code> retourneert de codering die R heeft gebruikt om de dummy-variabelen te maken:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(Salaries<span class="sc">$</span>sex)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Male
Female    0
Male      1</code></pre>
</div>
</div>
<p>R heeft een dummy-variabele <code>sexMale</code> gemaakt die de waarde 1 aanneemt als het geslacht Male is en anders 0. De beslissing om mannen als 1 te coderen en vrouwen als 0 (basline) is willekeurig en heeft geen effect op de regressieberekening, maar verandert wel de interpretatie van de coëfficiënten.</p>
</section>
<section id="categorievariabelen-met-meer-dan-2-niveaus" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="categorievariabelen-met-meer-dan-2-niveaus"><span class="header-section-number">3.3</span> Categorievariabelen met meer dan 2 niveaus</h2>
<p>Over het algemeen wordt een categorische variabele met n niveaus omgezet in n-1 variabelen met elk twee niveaus. Deze n-1 nieuwe variabelen bevatten dezelfde informatie als de enkele variabele. Deze hercodering creëert een tabel met de naam <strong>contrastmatrix</strong>.</p>
<p>Zo heeft in <code>salarie</code> de variabele <code>rank</code> drie niveaus: “AsstProf”, “AssocProf” en “Prof”. Deze variabele kan dummy worden gecodeerd in twee variabelen, een genaamd <code>AssocProf</code> en een <code>Prof</code>:</p>
<ul>
<li>Als <code>rank</code> = AssocProf, dan zou de kolom <code>AssocProf</code> worden gecodeerd met een 1 en <code>Prof</code> met een 0.</li>
<li>Als <code>rank</code> = Prof, dan zou de kolom <code>AssocProf</code> worden gecodeerd met een 0 en <code>Prof</code> zou worden gecodeerd met een 1.</li>
<li>Als <code>rank</code> = AsstProf, dan worden beide kolommen <code>AssocProf</code> en <code>Prof</code> gecodeerd met een 0.</li>
</ul>
<p>Deze dummy-codering wordt automatisch uitgevoerd door R. Voor demonstratiedoeleinden kun je de functie <code>model.matrix()</code> gebruiken om een contrastmatrix te maken voor een factorvariabele.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(<span class="sc">~</span>rank, <span class="at">data =</span> Salaries)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(res[,<span class="sc">-</span><span class="dv">1</span>])</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  rankAssocProf rankProf
1             0        1
2             0        1
3             0        0
4             0        1
5             0        1
6             1        0</code></pre>
</div>
</div>
<p>Bij het bouwen van een lineair model zijn er verschillende manieren om categorische variabelen te coderen, ook wel contrastcoderingssystemen genoemd. De standaardoptie in R is om het eerste niveau van de factor als referentie te gebruiken en de overige niveaus te interpreteren ten opzichte van dit niveau.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Opmerking
</div>
</div>
<div class="callout-body-container callout-body">
<p>ANOVA (variantieanalyse) is een speciaal geval van een lineair model waarbij de voorspellers categorische variabelen zijn. En omdat R begrijpt dat ANOVA en regressie beide voorbeelden zijn van lineaire modellen, kun je de klassieke ANOVA-tabel extraheren uit het regressiemodel met behulp van de R-basis <code>anova()</code> functie of de <code>Anova()</code>functie in package <code>car</code>. Over het algemeen is de functie <code>Anova()</code> aan te raden omdat deze automatisch voor ongebalanceerde ontwerpen zorgt.</p>
</div>
</div>
<p>Resultaten voor een meervoudig regressiemodel.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> yrs.service <span class="sc">+</span> rank <span class="sc">+</span> discipline <span class="sc">+</span> sex, <span class="at">data =</span> Salaries)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">Anova</span>(model2)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type II tests)

Response: salary
              Sum Sq  Df F value  Pr(&gt;F)    
yrs.service 3.24e+08   1    0.63    0.43    
rank        1.03e+11   2  100.26 &lt; 2e-16 ***
discipline  1.74e+10   1   33.86 1.2e-08 ***
sex         7.77e+08   1    1.51    0.22    
Residuals   2.01e+11 391                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Wanneer je ook rekening houdt met andere variabelen (<code>yrs.service</code>, <code>rank</code> en <code>discipline</code>) zul je zien dat de categorische variabele <code>sex</code> niet langer significant geassocieerd is met de variatie in <code>salary</code> tussen individuen. Belangrijke variabelen zijn <code>rank</code> en <code>discipline</code>.</p>
<p>Als je de contrasten van de categorische variabele wilt interpreteren, gebruik dan de volgende opdracht.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Kopieer naar klembord" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ yrs.service + rank + discipline + sex, 
    data = Salaries)

Residuals:
   Min     1Q Median     3Q    Max 
-64202 -14255  -1533  10571  99163 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    68351.7     4482.2   15.25  &lt; 2e-16 ***
yrs.service      -88.8      111.6   -0.80  0.42696    
rankAssocProf  14560.4     4098.3    3.55  0.00043 ***
rankProf       49159.6     3834.5   12.82  &lt; 2e-16 ***
disciplineB    13473.4     2315.5    5.82  1.2e-08 ***
sexMale         4771.2     3878.0    1.23  0.21931    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 22700 on 391 degrees of freedom
Multiple R-squared:  0.448, Adjusted R-squared:  0.441 
F-statistic: 63.4 on 5 and 391 DF,  p-value: &lt;2e-16</code></pre>
</div>
</div>
<p>Zo is te zien dat het afkomstig zijn uit discipline B (toegepaste afdelingen) significant geassocieerd is met een gemiddelde stijging van 13473,38 in salaris in vergelijking met discipline A (theoretische afdelingen).</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Opmerking
</div>
</div>
<div class="callout-body-container callout-body">
<p>Sommige categorische variabelen hebben geordende niveaus. Deze kunnen worden geconverteerd naar numerieke waarden, gerangschikt van laag naar hoog.</p>
</div>
</div>


<div id="refs" class="references csl-bib-body" role="doc-bibliography" style="display: none">
<div id="ref-FisherExactTest2022" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin"><strong>1</strong>. </div><div class="csl-right-inline"><span>‘<a href="https://en.wikipedia.org/w/index.php?title=Fisher%27s_exact_test&amp;oldid=1117572309">Fisher’s Exact Test</a>’</span>, <em>Wikipedia</em>, (2022).</div>
</div>
<div id="ref-UnusualObservationsOutlier" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin"><strong>2</strong>. </div><div class="csl-right-inline"><span>‘<span>Unusual Observations - Outlier, Leverage, and Influential Points</span>’</span>, <a href="https://www.theopeneducator.com/doe/Regression/outlier-leverage-influential-points">https://www.theopeneducator.com/doe/Regression/outlier-leverage-influential-points</a>.</div>
</div>
<div id="ref-buijsStatistiekOmMee1991" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin"><strong>3</strong>. </div><div class="csl-right-inline"><strong>Buijs, A.</strong>, <span>‘<span>Statistiek om mee te werken</span>’</span>, Third dr., <span>Stenfert Kroese</span>, (1991).</div>
</div>
<div id="ref-chouldechovaRegressionDiagnosticPlots" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin"><strong>4</strong>. </div><div class="csl-right-inline"><strong>Chouldechova, A.</strong>, <span>‘Regression Diagnostic Plots’</span>, <a href="https://www.andrew.cmu.edu/user/achoulde/94842/homework/regression_diagnostics.html">https://www.andrew.cmu.edu/user/achoulde/94842/homework/regression_diagnostics.html</a>.</div>
</div>
<div id="ref-datacampLinearRegressionTutorial" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin"><strong>5</strong>. </div><div class="csl-right-inline"><strong>Datacamp</strong>, <span>‘R <span>Linear Regression Tutorial</span>: Lm <span>Function</span> in <span>R</span> with <span>Code Examples</span>’</span>, <a href="https://www.datacamp.com/tutorial/linear-regression-R">https://www.datacamp.com/tutorial/linear-regression-R</a>.</div>
</div>
<div id="ref-doringFindingSuitableLinear2018" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin"><strong>6</strong>. </div><div class="csl-right-inline"><strong>Döring, M.</strong>, <span>‘Finding a <span>Suitable Linear Model</span> for <span>Ozone Prediction</span>’</span>, <em>Data Science Blog</em>, 2018. <a href="https://www.datascienceblog.net/post/machine-learning/improving_ozone_prediction/">https://www.datascienceblog.net/post/machine-learning/improving_ozone_prediction/</a>.</div>
</div>
<div id="ref-doringInterpretingLinearPrediction2018" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin"><strong>7</strong>. </div><div class="csl-right-inline"><strong>Döring, M.</strong>, <span>‘Interpreting <span>Linear Prediction Models</span>’</span>, <em>Data Science Blog</em>, 2018. <a href="https://www.datascienceblog.net/post/machine-learning/linear_models/">https://www.datascienceblog.net/post/machine-learning/linear_models/</a>.</div>
</div>
<div id="ref-hackerearthBeginnersGuideRegression" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin"><strong>8</strong>. </div><div class="csl-right-inline"><strong>Hackerearth</strong>, <span>‘Beginners <span>Guide</span> to <span>Regression Analysis</span> and <span>Plot Interpretations</span>’</span>, <a href="https://www.hackerearth.com/practice/machine-learning/machine-learning-algorithms/beginners-guide-regression-analysis-plot-interpretations/tutorial/">https://www.hackerearth.com/practice/machine-learning/machine-learning-algorithms/beginners-guide-regression-analysis-plot-interpretations/tutorial/</a>.</div>
</div>
<div id="ref-hackerearthPracticalGuideLogistic" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin"><strong>9</strong>. </div><div class="csl-right-inline"><strong>Hackerearth</strong>, <span>‘Practical <span>Guide</span> to <span>Logistic Regression Analysis</span> in <span>R</span>’</span>, <a href="https://www.hackerearth.com/practice/machine-learning/machine-learning-algorithms/logistic-regression-analysis-r/tutorial/">https://www.hackerearth.com/practice/machine-learning/machine-learning-algorithms/logistic-regression-analysis-r/tutorial/</a>.</div>
</div>
<div id="ref-kassambaraLogisticRegressionEssentials2018" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin"><strong>10</strong>. </div><div class="csl-right-inline"><strong>Kassambara, A.</strong>, <span>‘Logistic <span>Regression Essentials</span> in <span>R</span>’</span>, 2018. <a href="http://www.sthda.com/english/articles/36-classification-methods-essentials/151-logistic-regression-essentials-in-r/">http://www.sthda.com/english/articles/36-classification-methods-essentials/151-logistic-regression-essentials-in-r/</a>.</div>
</div>
<div id="ref-kassambaraMachineLearningEssentials2018" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin"><strong>11</strong>. </div><div class="csl-right-inline"><strong>Kassambara, A.</strong>, <span>‘Machine <span>Learning Essentials</span>: <span>Practical Guide</span> in <span>R</span>’</span>, 1st edition dr., (2018).</div>
</div>
<div id="ref-universityofvirginiaUnderstandingDiagnosticPlots" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin"><strong>12</strong>. </div><div class="csl-right-inline"><strong>University of Virginia</strong>, <span>‘Understanding <span>Diagnostic Plots</span> for <span>Linear Regression Analysis</span> | <span>University</span> of <span>Virginia Library Research Data Services</span> + <span>Sciences</span>’</span>, <a href="https://data.library.virginia.edu/diagnostic-plots/">https://data.library.virginia.edu/diagnostic-plots/</a>.</div>
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Gekopieerd!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Gekopieerd!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
    var links = window.document.querySelectorAll('a:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
          // default icon
          link.classList.add("external");
      }
    }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./diagnoses.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Diagnostische grafieken</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./correlatie.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Correlatie</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>